### ISSUE TITLE
The new in-game help does not scale well

### ISSUE THREAD

**Issue by hron84** [joshiejack/Enchiridion#42] opened 2015-04-02 23:39 UTC
On "GUI Scale: Auto" setting the help screen overflows from the displayed area vertically on 16:9 screen (for me under Linux at 1366x768 w/ 96 dpi). While it is not a problem for the sidebar, it causes a problem for the content pane.

Even if the help says editing book is requires a scale configuring I do not think the help itself should not scale well - mostly because it contains merely a wall of text.

**Version:** Enchiridion 2-1.7.10-2.0e and Enchiridion 1-1.7.X-1.2b
**Modpack:** [FTB Regrowth](http://forum.feed-the-beast.com/threads/1-7-10-regrowth-a-wip-hqm-pack-now-listed.57184/)

**Comment by joshiejack** [comment] 2015-04-03 00:37
It doesnt scale. It's always the same width, 1000 and a bit pixels wide. I made it this way as the cicilopedia is fixed width too. 2.1 has plans for scaling when resolutions are too small though. But this is a suggestion not a bug.

**Comment by hron84** [comment] 2015-04-03 09:52
@joshiejack Even if I agree your arguments from my point of view, it is a bug for users since I can't see a way to be able to read the rest of the text. OK, I started it reading because I waited my crops to grow but maybe someone want to create custom books - and that text is definitely longer than it is displayed.

Can we workaround it by slightly decreasing the **height** to 768 px? I guess the text component can handle if the text does not fit well.

**Comment by joshiejack** [comment] 2015-04-03 13:03
Can you screenshot what ur talking about. You just mentioned books, and those are scaling to gui size. And they fit in all gui scales for me. The pedia however, doesn't always fit across the width of the screen. Height doesn't matter since you can scroll up/down.

**Comment by hron84** [comment] 2015-04-04 11:16
@joshiejack no, i mentioned the... Pedia, it is how you call the Enchiridion's own in-game help to creating custom books?

Height is matter since the Pedia sets bigger height than the screen's actual height and yes, the text is scrollable - but only if it is much longer thant the help's actual height. If it is fits to the own height of the help but not to the screen's actual height, the text does not become scrollable. 

Width (horizontal dimension) is not affected with this issue in any way.

I'll post a screenshot soon but you can reproduce the error on a screen that has 768px **height**

**Comment by joshiejack** [comment] 2015-04-04 15:56
The wikis height is based on minecraft height.

**Comment by joshiejack** [comment] 2016-02-28 21:00
Wiki is removed in 1.8, due to me not really caring for it and no actual use as it is less immersive, so non issue, so closing.

**Closed by joshiejack** 2016-02-28 21:00 UTC
Labels: enhancement
