### ISSUE TITLE
A small error I am seeing in the console .

### ISSUE THREAD

**Issue by crunkazcanbe** [joshiejack/Enchiridion#34] opened 2015-02-20 06:01 UTC
As the title says heres the error

[00:56:02] [Client thread/ERROR] [Enchiridion]: Enchiridion had an issue when trying to load the item: class com.rwtema.extrautils.multipart.microblock.ItemMicroBlock
[00:56:02] [Client thread/ERROR] [Enchiridion]: Enchiridion had an issue when trying to load the item: class codechicken.microblock.ItemMicroPart

Is there anyway I can fix this ?

**Comment by joshiejack** [comment] 2015-02-20 06:28
No, thanks for reporting though :)

Means I can look in to what's causing the issue with loading them :)

**Comment by GirafiStudios** [comment] 2015-12-01 21:42
Can't reproduce

**Comment by crunkazcanbe** [comment] 2015-12-02 00:43
Ok 1 year later .. it was another mod causing this is believe hell I forget .



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On Tue, Dec 01, 2015 at 4:42 PM, Girafi < notifications@github.com [notifications@github.com] > wrote:
Can't reproduce

—
Reply to this email directly or view it on GitHub
[https://github.com/joshiejack/Enchiridion/issues/34#issuecomment-161104591] .[https://github.com/notifications/beacon/AFZoAHCaA-x4NOUrlzn874CHHaaHalhaks5pLgvCgaJpZM4DjIBq.gif]

**Comment by GirafiStudios** [comment] 2015-12-02 00:50
Okay :)
If this is no longer a problem, please close the issue, thanks :)

**Closed** 2016-02-28 20:59 UTC
Labels: bug, compatibility
