### ISSUE TITLE
Can't get my book to load

### ISSUE THREAD

**Issue by TheUnChosenOne** [joshiejack/Enchiridion#90] opened 2016-11-02 21:16 UTC
i am using enchiridion v3 but every time i make a book and it will not load on the 3rd time i run the game.

**Comment by joshiejack** [comment] 2016-11-03 17:49
provide proof

**Comment by TheUnChosenOne** [comment] 2016-11-04 22:55
https://imgur.com/a/2pc57
is the proof good for you

**Comment by joshiejack** [comment] 2016-11-05 00:01
I would ask for the json but it's been so long since I've worked on Enchiridion I've forgot what it's supposed to look like xD.

**Comment by TheUnChosenOne** [comment] 2016-11-05 00:24
lol

**Comment by TheUnChosenOne** [comment] 2016-11-05 00:30
if i just make a book it will be ok but when i start editing it and adding more than one page it will load the first time i save and quit the game the second time is iffy but the third time i get on minecraft it will not load

**Comment by TheUnChosenOne** [comment] 2016-11-05 01:29
https://dl.dropboxusercontent.com/u/92193552/ThePack.json

**Comment by GirafiStudios** [comment] 2016-11-12 23:07
Thanks for the report @jackmaster9000 !
This seem to be an issue with Enchiridion support in Progression. Maybe you have removed Progression from your pack?
Closing this, since it is not caused by Enchiridion. I suggest you go report it to Progression at https://github.com/joshiejack/Progression :)

**Closed as completed by GirafiStudios** 2016-11-12 23:07 UTC
Labels: invalid, compatibility
